### ISSUE TITLE
[FP Written Report] Write down your reflection here

### ISSUE THREAD

**Issue by imbensonchiu** [112-1-Database-Management-Final-Project/ntu-book#43]
- Write down 100 ~ 150 words in English (feel free using GPT for translation)
- **Due: 2023/12/15 (Fri.) 23:59**

**Comment by imbensonchiu** [comment]
In this semester's final project, I took on the role of Project Manager, responsible for leading the team in brainstorming and discussions, establishing the overall workflow of the team, and organizing and supervising the execution progress of team members.

Drawing upon my extensive experience in past team collaborations and benefiting from the diligent cooperation of team members, this project has been systematically well-organized from the beginning to the present. Every task has been carried out smoothly, and each meeting has been conducted with remarkable efficiency. Overall, it has been a delightful project collaboration, providing me with valuable learning and experiences.

**Comment by ZaiKuku** [comment]
In conclusion, my experience with database management in this semester has been both challenging and rewarding. Throughout the course, I gained a comprehensive understanding of database design, implementation, and optimization. The hands-on projects provided valuable insights into real-world applications, allowing me to apply theoretical knowledge to practical scenarios.

The collaborative nature of the course fostered teamwork and communication skills, as we worked together on complex database projects. Overall, this experience has equipped me with a solid foundation in database management, and I am confident that the skills acquired will prove invaluable in future endeavors within the field.

**Comment by quevenliu** [comment]
Although I had experiences developing backend website, this is my first time to tackle with a relatively complex database and to cooperate with several people on the task of designing a database. In the development process, I realize that although writing a detailed document can be tedious sometimes, however, I gradually realize that it is worthwhile since it can save a lot of communication overheads in the future. 

Thanks for all group members who do their job perfectly and punctually. The development process will not be this smooth without you guys.

**Comment by yenting-biao** [comment]
It is my first time working on a group coding project, and everything feels new and challenging. Initially assigned to handle the backend, I was worried because of my limited experience with Git and Github, as well as my unfamiliarity with backend website development. However, as I progressed through the semester's Web Programming course of the EE department, my confidence grew, and my concerns about this project faded away. Despite gaining familiarity with full-stack website development, this project has been a tremendous learning experience for me. I've discovered how to effectively collaborate with team members while coding, and I've come to realize that managing a relatively complex database is no easy feat. Contrary to my initial belief that coding would be the most challenging aspect, designing the database for our system turned out to be the most demanding part of the project. It is not easy to design a good database. In conclusion, this project has deepened my understanding of database management, and surprisingly, I've found that developing backend is quite tedious for me.
