### ISSUE TITLE
Failed to add comment. Reason: duplicate key value violates unique constraint "comments_pkey"

### ISSUE THREAD

**Issue by ZaiKuku** [112-1-Database-Management-Final-Project/ntu-book#47]
![image](https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/107979268/1b011cc9-51d2-460d-acec-b0f6abae2442)

留言都會有這個錯誤

**Comment by togimoto** [comment]
Looks like this error also happens when inserting into `USEDBOOK`, and likely any other table that uses a serial ID. This is because each table already has some data, so the first few serial IDs are taken, but PostgreSQL does not know this and is trying to insert starting from ID = 1. Perhaps this could be fixed by adding a constraint that is something like `DEFAULT nextval()`?

**Comment by imbensonchiu** [comment]
<img width="1043" alt="image" src="https://github.com/112-1-Database-Management-Final-Project/ntu-book/assets/96575609/0177e057-ad40-4ea4-9909-b1bd60d3ae78">

因為 usedbookid 已經是 PK 了，沒有辦法直接把他的 data type 改成 serial 以及增加預設值，短時間內可能無法在資料庫這邊立即解決。

想問後端有沒有什麼替代的方案

**Comment by imbensonchiu** [comment]
我發現解法了，請去檢查 PR #49
